version: '3.7'
services:
  postgres:
    image: postgres:13
    container_name: nestjs_starter
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: nestjs_starter
      POSTGRES_USER: nestjs_starter
      POSTGRES_PASSWORD: nestjs_starter
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
