export enum ErrorEnum {
	USER_NOT_FOUND = 'USER_NOT_FOUND',
	TOKEN_EXPRIED = 'TOKEN_EXPRIED',
	INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
	INVALID_TOKEN = 'INVALID_TOKEN',
	INVALID_REFRESH_TOKEN = 'INVALID_REFRESH_TOKEN',
	INVALID_RESET_TOKEN = 'INVALID_RESET_TOKEN',
	WRONG_PASSWORD = 'WRONG PASSWROD',
}
